"""esquema inicial

Revision ID: 3ca4ff45b789
Revises: 
Create Date: 2026-09-20 12:10:03.129847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3ca4ff45b789'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moneda',
    sa.Column('id_moneda', sa.Integer(), nullable=False),
    sa.Column('codigo_iso', sa.String(length=3), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('simbolo', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id_moneda', name=op.f('pk_moneda')),
    sa.UniqueConstraint('codigo_iso', name=op.f('uq_moneda_codigo_iso'))
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Enum('ADMIN_SIS', 'ADMIN_NEG', 'CLIENTE', name='rolcodigo'), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_rol', name=op.f('pk_rol')),
    sa.UniqueConstraint('codigo', name=op.f('uq_rol_codigo'))
    )
    op.create_table('tienda',
    sa.Column('id_tienda', sa.Integer(), nullable=False),
    sa.Column('ruc', sa.String(length=20), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=200), nullable=False),
    sa.Column('giro', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_tienda', name=op.f('pk_tienda')),
    sa.UniqueConstraint('ruc', name=op.f('uq_tienda_ruc'))
    )
    op.create_table('unidad_medida',
    sa.Column('id_unidad', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_unidad', name=op.f('pk_unidad_medida')),
    sa.UniqueConstraint('codigo', name=op.f('uq_unidad_medida_codigo'))
    )
    op.create_table('marca',
    sa.Column('id_marca', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tienda.id_tienda'], name=op.f('fk_marca_tienda_id_tienda')),
    sa.PrimaryKeyConstraint('id_marca', name=op.f('pk_marca'))
    )
    op.create_table('proveedor',
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('ruc', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tienda.id_tienda'], name=op.f('fk_proveedor_tienda_id_tienda')),
    sa.PrimaryKeyConstraint('id_proveedor', name=op.f('pk_proveedor'))
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id_rol'], name=op.f('fk_usuario_rol_id_rol')),
    sa.ForeignKeyConstraint(['tienda_id'], ['tienda.id_tienda'], name=op.f('fk_usuario_tienda_id_tienda')),
    sa.PrimaryKeyConstraint('id_usuario', name=op.f('pk_usuario')),
    sa.UniqueConstraint('username', name=op.f('uq_usuario_username'))
    )
    op.create_table('bitacora',
    sa.Column('id_bitacora', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('entidad', sa.Enum('TIENDA', 'PRODUCTO', 'CLIENTE', 'USUARIO', name='entidadbitacora'), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.Enum('ALTA', 'BAJA', 'MODIFICACION', name='accionbitacora'), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('detalle', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], name=op.f('fk_bitacora_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id_bitacora', name=op.f('pk_bitacora'))
    )
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=20), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('nombres', sa.String(length=150), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tienda.id_tienda'], name=op.f('fk_cliente_tienda_id_tienda')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], name=op.f('fk_cliente_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id_cliente', name=op.f('pk_cliente')),
    sa.UniqueConstraint('usuario_id', name=op.f('uq_cliente_usuario_id'))
    )
    op.create_table('producto',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('unidad_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('precio_contado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_lista', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('permite_fin_de_mes', sa.Boolean(), nullable=False),
    sa.Column('permite_cuotas', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id_marca'], name=op.f('fk_producto_marca_id_marca')),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id_proveedor'], name=op.f('fk_producto_proveedor_id_proveedor')),
    sa.ForeignKeyConstraint(['tienda_id'], ['tienda.id_tienda'], name=op.f('fk_producto_tienda_id_tienda')),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidad_medida.id_unidad'], name=op.f('fk_producto_unidad_id_unidad_medida')),
    sa.PrimaryKeyConstraint('id_producto', name=op.f('pk_producto'))
    )
    op.create_table('condicion_credito',
    sa.Column('id_condicion', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('moneda_id', sa.Integer(), nullable=False),
    sa.Column('tasa_compensatoria', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('tipo_tasa_comp', sa.Enum('NOMINAL', 'EFECTIVA', name='tipotasa'), nullable=False),
    sa.Column('plazo_tasa_comp_dias', sa.Integer(), nullable=False),
    sa.Column('capitaliz_comp_dias', sa.Integer(), nullable=True),
    sa.Column('tasa_moratoria', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('tipo_tasa_mora', sa.Enum('NOMINAL', 'EFECTIVA', name='tipotasa'), nullable=False),
    sa.Column('plazo_tasa_mora_dias', sa.Integer(), nullable=False),
    sa.Column('capitaliz_mora_dias', sa.Integer(), nullable=True),
    sa.Column('limite_credito', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_meses', sa.Integer(), nullable=False),
    sa.Column('dia_corte', sa.Integer(), nullable=False),
    sa.Column('dia_pago', sa.Integer(), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id_cliente'], name=op.f('fk_condicion_credito_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['moneda_id'], ['moneda.id_moneda'], name=op.f('fk_condicion_credito_moneda_id_moneda')),
    sa.PrimaryKeyConstraint('id_condicion', name=op.f('pk_condicion_credito'))
    )
    op.create_table('estado_cuenta',
    sa.Column('id_estado_cuenta', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('fecha_corte', sa.Date(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('total_capital', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_interes_comp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_interes_mora', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_pagar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('EMITIDO', 'PAGADO', 'VENCIDO', name='estadocuentaestado'), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id_cliente'], name=op.f('fk_estado_cuenta_cliente_id_cliente')),
    sa.PrimaryKeyConstraint('id_estado_cuenta', name=op.f('pk_estado_cuenta'))
    )
    op.create_table('compra',
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('condicion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_compra', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modalidad', sa.Enum('FIN_DE_MES', 'CUOTAS', name='modalidadcompra'), nullable=False),
    sa.Column('num_cuotas', sa.Integer(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tep_aplicada', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('fecha_corte_asignada', sa.Date(), nullable=False),
    sa.Column('fecha_primer_pago', sa.Date(), nullable=False),
    sa.Column('dias_gracia', sa.Integer(), nullable=False),
    sa.Column('capital_capitalizado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('VIGENTE', 'CANCELADA', 'ANULADA', name='estadocompra'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id_cliente'], name=op.f('fk_compra_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['condicion_id'], ['condicion_credito.id_condicion'], name=op.f('fk_compra_condicion_id_condicion_credito')),
    sa.PrimaryKeyConstraint('id_compra', name=op.f('pk_compra'))
    )
    op.create_table('cuota',
    sa.Column('id_cuota', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('numero_cuota', sa.Integer(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amortizacion', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_cuota', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_final', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'FACTURADA', 'PAGADA', 'VENCIDA', name='estadocuota'), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.id_compra'], name=op.f('fk_cuota_compra_id_compra')),
    sa.PrimaryKeyConstraint('id_cuota', name=op.f('pk_cuota'))
    )
    op.create_table('detalle_compra',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.id_compra'], name=op.f('fk_detalle_compra_compra_id_compra')),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id_producto'], name=op.f('fk_detalle_compra_producto_id_producto')),
    sa.PrimaryKeyConstraint('id_detalle', name=op.f('pk_detalle_compra'))
    )
    op.create_table('estado_cuenta_detalle',
    sa.Column('id_detalle_ec', sa.Integer(), nullable=False),
    sa.Column('estado_cuenta_id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=True),
    sa.Column('cuota_id', sa.Integer(), nullable=True),
    sa.Column('tipo_item', sa.Enum('COMPRA', 'CUOTA', 'INT_COMPENSATORIO', 'INT_MORATORIO', name='tipoitemestadocuenta'), nullable=False),
    sa.Column('fecha_referencia', sa.Date(), nullable=False),
    sa.Column('dias_transcurridos', sa.Integer(), nullable=False),
    sa.Column('tasa_aplicada', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.id_compra'], name=op.f('fk_estado_cuenta_detalle_compra_id_compra')),
    sa.ForeignKeyConstraint(['cuota_id'], ['cuota.id_cuota'], name=op.f('fk_estado_cuenta_detalle_cuota_id_cuota')),
    sa.ForeignKeyConstraint(['estado_cuenta_id'], ['estado_cuenta.id_estado_cuenta'], name=op.f('fk_estado_cuenta_detalle_estado_cuenta_id_estado_cuenta')),
    sa.PrimaryKeyConstraint('id_detalle_ec', name=op.f('pk_estado_cuenta_detalle'))
    )
    op.create_table('pago',
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado_cuenta_id', sa.Integer(), nullable=True),
    sa.Column('cuota_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora_pago', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_mora_aplicado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_interes_comp_aplicado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_capital_aplicado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('REGISTRADO', 'ANULADO', name='estadopago'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id_cliente'], name=op.f('fk_pago_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['cuota_id'], ['cuota.id_cuota'], name=op.f('fk_pago_cuota_id_cuota')),
    sa.ForeignKeyConstraint(['estado_cuenta_id'], ['estado_cuenta.id_estado_cuenta'], name=op.f('fk_pago_estado_cuenta_id_estado_cuenta')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], name=op.f('fk_pago_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id_pago', name=op.f('pk_pago'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    op.drop_table('estado_cuenta_detalle')
    op.drop_table('detalle_compra')
    op.drop_table('cuota')
    op.drop_table('compra')
    op.drop_table('estado_cuenta')
    op.drop_table('condicion_credito')
    op.drop_table('producto')
    op.drop_table('cliente')
    op.drop_table('bitacora')
    op.drop_table('usuario')
    op.drop_table('proveedor')
    op.drop_table('marca')
    op.drop_table('unidad_medida')
    op.drop_table('tienda')
    op.drop_table('rol')
    op.drop_table('moneda')
    # ### end Alembic commands ###
