"""sincroniza estado_cuenta con version de Ruth

Revision ID: cce6249bff1e
Revises: ee2ab72dcc67
Create Date: 2026-09-21 16:28:06.111000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cce6249bff1e'
down_revision: Union[str, None] = 'ee2ab72dcc67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('estado_cuenta_detalle', 'fecha_referencia',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('estado_cuenta_detalle', 'dias_transcurridos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('estado_cuenta_detalle', 'tasa_aplicada',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('estado_cuenta_detalle', 'tasa_aplicada',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               nullable=False)
    op.alter_column('estado_cuenta_detalle', 'dias_transcurridos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('estado_cuenta_detalle', 'fecha_referencia',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
